spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.106:1521:cnbi
    username: BRDB_1103
    password: cnbi2020

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

server:
  port: 8088
