spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.106:1521:cnbi
    driver: oracle.jdbc.driver.OracleDriver
    username: BRDB_1103
    password: cnbi2020

mybatis:
  mapper-locations:
    -classpath: mapper/*.xml
